server:
  port: 8781

spring:
  application:
    name: zuul-service

  cloud:
      zookeeper:
        discovery:
          root: /spring-cloud-service
        connect-string: 192.168.186.1:2181

zuul:
  ignored-services: new String('*')
  routes:
    user-service: /users/**
    admin-service: /admins/**
  ignore-security-headers: false
  sensitive-headers: xx

logging:
  level:
    root: info
    org.springframework.web: info

management:
  security:
    enabled: false