server:
  port: 8771

spring:
  application:
    name: turbine-service

  cloud:
    zookeeper:
      discovery:
        root: /spring-cloud-service
      connect-string: 192.168.186.1:2181

turbine:
  app-config: admin-service,user-service
  cluster-name-expression: new String('default')

logging:
  level:
    root: info
    org.springframework.web: info
